# Generated by Django 6.0.6 on 2026-07-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cancellations_month',
            field=models.IntegerField(default=3, help_text='Número de cancelamentos do usuário no mês'),
        ),
    ]
