# Generated by Django 6.0.6 on 2026-06-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Descrição do serviço solicitado')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('scheduled', 'Agendado'), ('rejected', 'Rejeitado'), ('in_displacement', 'Em deslocamento'), ('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('rated', 'Avaliado'), ('canceled_by_client', 'Cancelado pelo cliente'), ('canceled_by_provider', 'Cancelado pelo prestador de serviço')], default='pending', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Valor combinado no chat', max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Método de pagamento combinado (ex: PIX, Dinheiro)', max_length=50, null=True)),
                ('displacement_start', models.DateTimeField(blank=True, help_text='Início da janela de deslocamento', null=True)),
                ('displacement_end', models.DateTimeField(blank=True, help_text='Fim da janela de deslocamento', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da categoria (ex: Encanador, Eletricista)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descrição da categoria', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('scheduled', 'Agendado'), ('rejected', 'Rejeitado'), ('in_displacement', 'Em deslocamento'), ('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('rated', 'Avaliado'), ('canceled_by_client', 'Cancelado pelo cliente'), ('canceled_by_provider', 'Cancelado pelo prestador de serviço')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('scheduled', 'Agendado'), ('rejected', 'Rejeitado'), ('in_displacement', 'Em deslocamento'), ('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('rated', 'Avaliado'), ('canceled_by_client', 'Cancelado pelo cliente'), ('canceled_by_provider', 'Cancelado pelo prestador de serviço')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
