# Generated by Django 6.0.6 on 2026-07-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('scheduled', 'Agendado'), ('in_displacement', 'Em deslocamento'), ('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('rated', 'Avaliado'), ('canceled_by_client', 'Cancelado pelo cliente'), ('canceled_by_provider', 'Cancelado pelo prestador de serviço')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicestatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('scheduled', 'Agendado'), ('in_displacement', 'Em deslocamento'), ('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('rated', 'Avaliado'), ('canceled_by_client', 'Cancelado pelo cliente'), ('canceled_by_provider', 'Cancelado pelo prestador de serviço')], max_length=20),
        ),
        migrations.AlterField(
            model_name='servicestatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('scheduled', 'Agendado'), ('in_displacement', 'Em deslocamento'), ('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('rated', 'Avaliado'), ('canceled_by_client', 'Cancelado pelo cliente'), ('canceled_by_provider', 'Cancelado pelo prestador de serviço')], max_length=20, null=True),
        ),
    ]
