# Generated by Django 6.0.6 on 2026-06-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Conteúdo da mensagem')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
